version: '3'
services:
  app:
    container_name: ctts
    restart: always
    build: .
    ports:
      - '3000:3000'
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
